"""现金流量表定义 — 会小企03表"""
from reports.dsl import (
    Field, Bucket,
    SUM_FIELDS, SUM_CLASSIFIED, OPENING,
)


CASH_FLOW = [
    # ── 经营活动 ──
    Field("CF01", "销售产成品、商品、提供劳务收到的现金",
        source=SUM_CLASSIFIED(["CF01"]),
    ),
    Field("CF02", "收到其他与经营活动有关的现金",
        source=SUM_CLASSIFIED(["CF02"]),
    ),
    Field("CF03", "购买原材料、商品、接受劳务支付的现金",
        source=SUM_CLASSIFIED(["CF03"]),
    ),
    Field("CF04", "支付的职工薪酬",
        source=SUM_CLASSIFIED(["CF04"]),
    ),
    Field("CF05", "支付的税费",
        source=SUM_CLASSIFIED(["CF05"]),
    ),
    Field("CF06", "支付其他与经营活动有关的现金",
        source=SUM_CLASSIFIED(["CF06"]),
    ),

    Field("operating_inflows", "经营活动现金流入",
        source=SUM_FIELDS(["CF01", "CF02"]),
    ),
    Field("operating_outflows", "经营活动现金流出",
        source=SUM_FIELDS(["CF03", "CF04", "CF05", "CF06"]),
    ),
    Field("net_operating", "经营活动现金流量净额",
        source=SUM_FIELDS(["operating_inflows", "operating_outflows"]),
    ),

    # ── 投资活动 ──
    Field("CF08", "收回投资收到的现金",
        source=SUM_CLASSIFIED(["CF08"]),
    ),
    Field("CF09", "取得投资收益收到的现金",
        source=SUM_CLASSIFIED(["CF09"]),
    ),
    Field("CF10", "处置固定资产、无形资产收回的现金净额",
        source=SUM_CLASSIFIED(["CF10"]),
    ),
    Field("CF11", "投资支付的现金",
        source=SUM_CLASSIFIED(["CF11"]),
    ),
    Field("CF12", "购建固定资产、无形资产支付的现金",
        source=SUM_CLASSIFIED(["CF12"]),
    ),

    Field("investing_inflows", "投资活动现金流入",
        source=SUM_FIELDS(["CF08", "CF09", "CF10"]),
    ),
    Field("investing_outflows", "投资活动现金流出",
        source=SUM_FIELDS(["CF11", "CF12"]),
    ),
    Field("net_investing", "投资活动现金流量净额",
        source=SUM_FIELDS(["investing_inflows", "investing_outflows"]),
    ),

    # ── 筹资活动 ──
    Field("CF14", "取得借款收到的现金",
        source=SUM_CLASSIFIED(["CF14"]),
    ),
    Field("CF15", "吸收投资者投资收到的现金",
        source=SUM_CLASSIFIED(["CF15"]),
    ),
    Field("CF16", "偿还借款本金支付的现金",
        source=SUM_CLASSIFIED(["CF16"]),
    ),
    Field("CF17", "偿还借款利息支付的现金",
        source=SUM_CLASSIFIED(["CF17"]),
    ),
    Field("CF18", "分配利润支付的现金",
        source=SUM_CLASSIFIED(["CF18"]),
    ),

    Field("financing_inflows", "筹资活动现金流入",
        source=SUM_FIELDS(["CF14", "CF15"]),
    ),
    Field("financing_outflows", "筹资活动现金流出",
        source=SUM_FIELDS(["CF16", "CF17", "CF18"]),
    ),
    Field("net_financing", "筹资活动现金流量净额",
        source=SUM_FIELDS(["financing_inflows", "financing_outflows"]),
    ),

    # ── 汇总 ──
    Field("net_cash_flow", "现金净增加额",
        source=SUM_FIELDS(["net_operating", "net_investing", "net_financing"]),
    ),
    Field("_beg_cash", None,
        source=OPENING("cash_balance"),
    ),
    Field("_beg_bank", None,
        source=OPENING("bank_balance"),
    ),
    Field("beginning_cash", "期初现金及现金等价物余额",
        source=SUM_FIELDS(["_beg_cash", "_beg_bank"]),
    ),
    Field("ending_cash", "期末现金及现金等价物余额",
        source=SUM_FIELDS(["beginning_cash", "net_cash_flow"]),
    ),
]
